{% set name = "rpdb" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8346f0dd498a1c30768af3d3528cdfe8086d8c057c9fccb5430b5aec32ae16ab

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - rpdb

about:
  home: http://tamentis.com/projects/rpdb
  license: ISC (ISCL)
  license_family: OTHER
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: pdb wrapper with remote access via tcp socket
  dev_url: https://github.com/tamentis/rpdb

extra:
  recipe-maintainers:
    - Bezier89
    - pg-hbk
